#app
server:
  port: 8081
  max-http-header-size: 10000000

#spring
spring:
  devtools:
    restart:
      enabled: false
#redis
  redis:
    host: localhost
    port: 6379
    timeout: 3000
    password:
    pool:
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis: 100000
# MYSQL DATABASE CONFIG
  datasource:
    url: jdbc:mysql://localhost:3306/epsilon?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

# Max file size.
  http:
    multipart:
      max-file-size: 1Mb
# Max request size.
      max-request-size: 10Mb

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.epsilon.core.entity
  #typeEnumsPackage: com.epsilon.core.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
    key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义sql注入器,不在推荐使用此方式进行配置,请使用自定义bean注入
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现,不在推荐使用此方式进行配置,请使用自定义bean注入
    #meta-object-handler: MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#xxl-job
### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080
### xxl-job executor address
    executor:
      appname: epsilon
      ip:
      port: 9999
      logpath: /Users/alexcai/workspace/geetion/geetion_predict/logs/xxl-job
      logretentiondays: -1
### xxl-job, access token
    accessToken:

#spark
spark:
  spark-home: .
  master: local[4]
  app-name: trainAPP
